EvidenceBase/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
               url(r'^admin/', include(admin.site.urls)),
               url(r'^', include('app.urls')),
               ]

app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
               url(r'^$', views.index, name='index'),
               url(r'^health', views.health, name='health'),
               url(r'^404', views.handler404, name='404'),
               url(r'^500', views.handler500, name='500'),
               ]

evidence-base/app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
               url(r'^$', views.index, name='index'),
               url(r'^dashboard$', views.dashboard, name='dashboard'),
               url(r'^health', views.health, name='health'),
               url(r'^404', views.handler404, name='404'),
               url(r'^500', views.handler500, name='500'),
               ]

evidence-base/board/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url('create/', views.add_board, name='create_board'),
    url('view/', views.view_board, name='view_board'),
]

evidence-base/evidence/evidence/urls.py
from django.conf.urls import url

from . import views
from django.views.generic import ListView
from evidence.views import EvidenceListFiltered


app_name='evidence'

urlpatterns = [
    url(r"^$",views.CreateEvidence.as_view(), name="create_evidence"),
    url(r"(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.EvidenceDetail.as_view(),name="single"),
    url(r"(?P<pk>\d+)/analysis/$",views.add_analysis_to_evidence,name="add_analysis_to_evidence"),
    url(r"(?P<pk>\d+)/update/$",views.EvidenceUpdate.as_view(),name="evidence_update"),
    url(r"^category/(?P<slug>[-\w]+)/$",views.EvidenceListFiltered.as_view(),name="filtered_evidence"),
    url(r"(?P<pk>\d+)/delete/$",views.EvidenceDelete.as_view(),name="evidence_delete"),


#   url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
#   url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
#   url('evidence/new', views.CreateEvidence, name='create_evidence'),
#   url('evidence/<int:pk>/', views.EvidenceDetail, name='evidence_detail'),
]

evidence-base/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.

#This a class for users, using Django's built in models.
#We can use this for user forms so Django takes care of the backend/
class User(auth.models.User, auth.models.PermissionsMixin):
    #This is to create a string representation of the user.
    def __str__(self):
        return "@{}".format(self.username)

evidence-base/attribute/models.py
from django.db import models

from django.conf import settings
from django.core.urlresolvers import reverse

import misaka
from django.contrib.auth import get_user_model
Current_user = get_user_model()

# Models from our applications here
from board.models import Board

# Create your models here.
class Attribute(models.Model):
    title = models.CharField(max_length=100, unique=False, blank=False)
    sub_title = models.CharField(max_length=100, blank=False)
    attribute_description = models.TextField(max_length=300, blank=False)

    user = models.ForeignKey(Current_user, related_name="attribute")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        #If you need to do something
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "attribute:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]

evidence-base/board/models.py
from django.db import models

from django.conf import settings
from django.core.urlresolvers import reverse

import misaka
from django.contrib.auth import get_user_model
Current_user = get_user_model()

# Models from our applications here


# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=100, unique=False, blank=False)
    sub_title = models.CharField(max_length=100, blank=False)
    attribute_description = models.TextField(max_length=300, blank=False)

    user = models.ForeignKey(Current_user, related_name="board")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        #If you need to do something
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "board:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]

evidence-base/category/models.py
from django.db import models

from django.conf import settings
from django.core.urlresolvers import reverse

import misaka
from django.contrib.auth import get_user_model
Current_user = get_user_model()

# Models from our applications here
from attribute.models import Attribute


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=100, unique=False, blank=False)
    sub_title = models.CharField(max_length=100, blank=False)
    category_description = models.TextField(max_length=300, blank=False)

    user = models.ForeignKey(Current_user, related_name="category")
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(allow_unicode=True, unique=False)


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        #If you need to do something
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "category:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]

evidence/models.py
from django.db import models

# Create your models here.

evidence-base/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

#Inheriting UserCreationForm from auth, this class helps forms create our users.
class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')#These are from contrib.auth but we're selecting which fields we want users to input.
        model = get_user_model()

    #This is so we can have custom labels on the above form (not necessary unless you need something custom)
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name' #A custom label for username
        self.fields['email'].label = 'Email Address'

evidence-base/evidence/evidence/forms.py
from django import forms

from evidence import models
from . models import Evidence, Analysis


class EvidenceForm(forms.ModelForm):
    class Meta:
        fields = ('title','contributors_note','website','publisher','publication_date','content_type','research_type','category')
        model = models.Evidence

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["category"].queryset = (
                models.Category.objects.filter(
                    pk__in=user.category.values_list("catgeory__pk")#Will need to change to not just user category but attribute category's
                )
            )


class AnalysisForm(forms.ModelForm):

    class Meta:
        model = models.Analysis
        fields = ('title', 'content_rating_1', 'content_rating_1_comment', 'content_rating_2', 'content_rating_2_comment',
        'content_rating_3', 'content_rating_3_comment','content_rating_4', 'content_rating_4_comment','content_rating_5', 'content_rating_5_comment',
        'source_rating_1', 'source_rating_1_comment','source_rating_2', 'source_rating_2_comment',
        'source_rating_3', 'source_rating_3_comment','source_rating_4', 'source_rating_4_comment','source_rating_5', 'source_rating_5_comment')

evidence-base/EvidenceBase/views.py
from django.views.generic import TemplateView


#These are tests for logged in and logged out views.
class TestPage(TemplateView):
    template_name = "tests.html"

class ThanksPage(TemplateView):
    template_name = "thanks.html"

#This is a class that inherits from TemplateView
class HomePage(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse("test"))
        return super().get(request, *args, **kwargs)

evidence-base/accounts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView

from . import forms
# Create your views here.

#This is for creating a new user.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')#After succesful signup, we reverse them back to the login page so they can login.
    template_name = 'accounts/signup.html'

evidence-base/app/views.py
from __future__ import unicode_literals

from django.http import JsonResponse
from django.http import Http404
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

def dashboard(request):
    return render(request, 'dashboard.html', {
        'country_evidence': [
            {
                'image': '/static/images/flags/'+country+'.png',
                'title': country.capitalize()
            } for country in ['kenya', 'rwanda', 'egypt', 'south-africa'] * 2
        ]
    })

def health(request):
    state = {"status": "UP"}
    return JsonResponse(state)


def handler404(request):
    return render(request, '404.html', status=404)

def handler500(request):
    return render(request, '500.html', status=500)

evidence-base/attribute/views.py
from django.shortcuts import render

# Create your views here.

evidence-base/board/views.py
from __future__ import unicode_literals

from django.shortcuts import render


def add_board(request):
    return render(request, 'board/add_board.html')


def view_board(request):
    return render(request, 'board/view_board.html', {
        'evidence_list': [
            {
                'time_elapsed': str(i) + ' hrs ago',
                'tags': ['tag #' + str(n) for n in [1, 2, 3]]
            } for i in [1, 2, 3, 4, 5]
        ],
        'contributors': [
            {'name': 'Jane Doe', 'role': 'practitioner'},
            {'name': 'Miley Jennifer', 'role': 'researcher'},
            {'name': 'Elaine Lwane', 'role': 'chairman'}
        ]
    })

evidence-base/category/views.py
from __future__ import unicode_literals

from django.shortcuts import render


def view_category_board(request):
    return render(request, 'category/category_base.html', {
        'evidence_list': [
            {
                'time_elapsed': str(i) + ' hrs ago',
                'tags': ['tag #' + str(n) for n in [1, 2, 3]]
            } for i in [1, 2, 3, 4, 5]
        ],
        'contributors': [
            {'name': 'Jane Doe', 'role': 'practitioner'},
            {'name': 'Miley Jennifer', 'role': 'researcher'},
            {'name': 'Elaine Lwane', 'role': 'chairman'}
        ]
    })

evidence-base/evidence/evidence/views.py
from django.shortcuts import render

from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.shortcuts import get_object_or_404, get_list_or_404
from django.shortcuts import redirect

#from django.db import IntegrityError

from django.views import generic
from evidence.models import Evidence, Analysis
from . import models
from . import forms
from .forms import AnalysisForm

from braces.views import SelectRelatedMixin

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

#This view allows users to add evidence to a category
class CreateEvidence(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('title','contributors_note','website','publisher','content_type','research_type','category')
    model = models.Evidence

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


#This view is used to retrieve a single piece of evidence
class EvidenceDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Evidence
    select_related = ("category", "user")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )

#This view updates a single piece of evidence
class EvidenceUpdate(generic.UpdateView):
    model = models.Evidence
    fields = ['title','contributors_note','website','publisher','publication_date','content_type','research_type','category']
    template_name_suffix = '_update_form'

#This view lists evidence, filtered by category.
class EvidenceListFiltered(generic.ListView):
    model = Evidence
    select_related = ("category", "user")
    template_name = 'evidence/evidence_list.html'

    def get_queryset(self):
        qs = self.model.objects.all()
        if self.kwargs.get('slug'):
            qs = qs.filter(category__slug=self.kwargs['slug'])
        return qs

class EvidenceDelete(generic.DeleteView):
    model = Evidence
#    success_url = reverse_lazy('evidence:filtered_evidence')
# Will resolve success url after user flow is complete


#This view is used to add analysis to a piece of evidence
def add_analysis_to_evidence(request, pk):
    evidence = get_object_or_404(Evidence, pk=pk)
    if request.method == "POST":
        form = AnalysisForm(request.POST)
        if form.is_valid():
            analysis = form.save(commit=False)
            analysis.evidence = evidence
            analysis.analyst  = request.user
            analysis.save()
            return redirect("evidence:single", username=evidence.user, pk=evidence.pk)
    else:
        analysis_form = AnalysisForm()
    return render(request, 'evidence/add_analysis_to_evidence.html', {'analysis_form': analysis_form})

evidence/views.py
from django.shortcuts import render

# Create your views here.

evidence-base/evidence/evidence/templates/evidence/_evidence.html
<div class="evidence media">
	<h3>{{ evidence.message_html|safe }}</h3>
	<div class="media-body">

		<strong>Title: {{ evidence.title }} </strong>
		<p>Contributor's Note: {{ evidence.contributors_note }}</p>
		<p>Publisher: {{ evidence.publisher }}</p>
		<p>Content Type: {{ evidence.content_type }}</p>
		<p>Research Type: {{ evidence.research_type }}</p>
		<strong>Added to {{ evidence.category }} by {{ evidence.user.username }} on {{ evidence.created_at }} </strong>
		<p>Last updated: {{ evidence.last_updated }}</p>
		<p><a href=" {{ evidence.website }}" >Link to Evidence</a></p>
		<p><a class="btn btn-default" href="{% url 'evidence:evidence_update' pk=evidence.pk %}">Update this Evidence</a></p>
		<p><a class="btn btn-primary" href="{% url 'evidence:filtered_evidence' slug=evidence.category.slug %}">View the Category</a></p>
		<p><a class="btn btn-danger" href="{% url 'evidence:evidence_delete' pk=evidence.pk %}">Delete Evidence</a></p>

		<h2>Analysis Summary</h2>
		<p> Evidence Strength: insert something dynamic to make me pretty </p>
		<h5>Key Findings</h5>
		<p> - {{ analysis.key_finding1 }}</p>
		<p> - {{ analysis.key_finding2 }}</p>
		<p> - {{ analysis.key_finding3 }}</p>

		<p><a class="btn btn-default" href="{% url 'evidence:add_analysis_to_evidence' pk=evidence.pk %}">Analyse Evidence</a></p>


		<strong> Detailed Analysis </strong>

		<hr>
			{% for analyses in evidence.analysis.all %}
			    <div class="analysis">
						<br>
							<h4>{{ analyses.title }}</h4>
							<div class="date">{{ analyses.created_at }}</div>
			        <strong>By {{ analyses.analyst }}</strong>

			        <p><strong> Content Rating Area 1 </strong> {{ analyses.content_rating_1 }}</p>
							<p>{{ analyses.content_rating_1_comment }}</p>

							<p><strong> Content Rating Area 2 </strong> {{ analyses.content_rating_2 }}</p>
							<p>{{ analyses.content_rating_2_comment }}</p>

							<p><strong> Content Rating Area 3 </strong> {{ analyses.content_rating_3 }}</p>
							<p>{{ analyses.content_rating_3_comment }}</p>

							<p><strong> Content Rating Area 4 </strong> {{ analyses.content_rating_4 }}</p>
							<p>{{ analyses.content_rating_4_comment|linebreaks }}</p>
						</br>
			    </div>
			{% empty %}
			    <p>No analysis here yet :(</p>
			{% endfor %}
		</hr>






<h6>Later, we'll add ratings here if any are given. Naturally, with logic around being logged in</h6>


		</div>
	</div>
</div>

evidence-base/evidence/evidence/templates/evidence/add_analysis_to_evidence.html
{% extends "evidence/evidence_base.html" %}
<h3>{{ evidence.message_html|safe }}</h3>



{% block evidence_content %}
<p><a href=" {{ evidence.website }}" >Link to Evidence</a></p>
<h1>New Analysis for WHY IS THIS STILL NOT DYNAMIC? {{ evidence.title }} </h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ analysis_form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>


{% endblock %}

evidence-base/evidence/evidence/templates/evidence/evidence_base.html
{% extends "base.html" %}

{% block content %}
<div class="evidence-page">
	<div class="container">
		<div class="row">
			{% block pre_evidence %} {% endblock %}
			{% block evidence_content %} {% endblock %}
			{% block post_evidence %} {% endblock %}
		</div>
	</div>
</div>
{% endblock %}

evidence-base/evidence/evidence/templates/evidence/evidence_confirm_delete.html
{% extends "evidence/evidence_base.html" %}

{% block evidence_content %}

<h1>{{ evidence.title }}</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?
    This action cannot be undone. </p>
    <input type="submit" value="Yes, Delete!" />
</form>

<script>
function goBack() {
    window.history.back()
}
</script>
<button onclick="goBack()">No, go back</button>


{% endblock %}

evidence-base/evidence/evidence/templates/evidence/evidence_detail.html
{% extends "evidence/evidence_base.html" %}
{% block evidence_content %}
<h3 class="media-heading">

  <time class="time"><a href="{% url 'evidence:single' username=evidence.user.username pk=evidence.pk %}">{{ evidence.title }}</a></time>

</h3>
  <div>
{% include "evidence/_evidence.html" %}
</div>
{% endblock %}

{% block post_evidence %}

<a class="btn btn-default" href="{% url 'evidence:add_analysis_to_evidence' pk=evidence.pk %}">Analyse Evidence</a>

{% endblock %}

evidence-base/evidence/evidence/templates/evidence/evidence_form.html
{% extends "evidence/evidence_base.html" %}

{% load bootstrap3 %}

{% block evidence_content %}
<h4>Add New Evidence</h4>
<form method="POST" action="{% url 'evidence:create_evidence' %}" id="EvidenceForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>

{% endblock %}

evidence-base/evidence/evidence/templates/evidence/evidence_list.html
{% extends "evidence/evidence_base.html" %}

{% block evidence_content %}

<h1>{{ evidence.category.title }}</h1>

<ul>
  {% for evidence in object_list %}
  <div class="evidencefeed">
    <br>
    <h3 class="media-heading">

      <time class="time"><a href="{% url 'evidence:single' username=evidence.user.username pk=evidence.pk %}">{{ evidence.title }}</a></time>

    </h3>
      <div class="date">{{ evidence.created_at }}</div>
      <strong>Added by {{ evidence.user }}</strong>
      <p> {{evidence.contributors_note}} </p>
      <strong>Category: {{ evidence.category }}</strong>

  {% empty %}
      <p>No evidence here yet :(</p>
  {% endfor %}
</div>
{% endblock %}

evidence-base/evidence/evidence/templates/evidence/evidence_update_form.html
{% extends "evidence/evidence_base.html" %}
{% block evidence_content %}

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update Evidence"/>
</form>

{% endblock %}